# Generated by Django 4.2.6 on 2023-11-19 00:27

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookAuthorModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='BookPublisherModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='BookRentalModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('itens', models.JSONField()),
                ('late', models.BooleanField(default=True)),
                ('delivered', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='CategoryItensModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='GuardianModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=14)),
                ('address', models.JSONField(default=api.models.address)),
                ('phone1', models.CharField(max_length=14)),
                ('phone2', models.CharField(max_length=14)),
                ('email', models.EmailField(max_length=254)),
                ('whats', models.CharField(max_length=14)),
                ('date_nasc', models.CharField(max_length=14)),
            ],
        ),
        migrations.CreateModel(
            name='TypeItemModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ItensModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('year_publish', models.DateField()),
                ('version', models.IntegerField()),
                ('count', models.IntegerField()),
                ('obs', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.bookauthormodel')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.categoryitensmodel')),
                ('plusher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.bookpublishermodel')),
            ],
        ),
        migrations.CreateModel(
            name='ExtendUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cpf', models.CharField(max_length=14)),
                ('address', models.JSONField(default=api.models.address)),
                ('phone1', models.CharField(max_length=14)),
                ('phone2', models.CharField(max_length=14)),
                ('phone_other1', models.CharField(max_length=14)),
                ('phone_other2', models.CharField(max_length=14)),
                ('whats', models.CharField(max_length=14)),
                ('date_nasc', models.CharField(max_length=14)),
                ('guardian', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.guardianmodel')),
            ],
        ),
    ]
