# Generated by Django 4.2.6 on 2024-01-19 21:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookauthormodel',
            options={'verbose_name': 'Author', 'verbose_name_plural': 'Autores'},
        ),
        migrations.AlterModelOptions(
            name='bookpublishermodel',
            options={'verbose_name': 'Editora', 'verbose_name_plural': 'Editoras'},
        ),
        migrations.AlterModelOptions(
            name='bookrentalmodel',
            options={'verbose_name': 'Aluguel', 'verbose_name_plural': 'Alugueis'},
        ),
        migrations.AlterModelOptions(
            name='categoryitensmodel',
            options={'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterModelOptions(
            name='guardianmodel',
            options={'verbose_name': 'Responsável', 'verbose_name_plural': 'Responsáveis'},
        ),
        migrations.AlterModelOptions(
            name='itensmodel',
            options={'verbose_name': 'Item', 'verbose_name_plural': 'Itens'},
        ),
        migrations.AlterModelOptions(
            name='typeitemmodel',
            options={'verbose_name': 'Tipo', 'verbose_name_plural': 'Tipos'},
        ),
        migrations.AddField(
            model_name='bookrentalmodel',
            name='client',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='extenduser',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
