# Generated by Django 4.2.6 on 2024-01-30 17:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_alter_bookauthormodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extenduser',
            name='date_nasc',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='extenduser',
            name='guardian',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.guardianmodel'),
        ),
        migrations.AlterField(
            model_name='extenduser',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
